### ISSUE TITLE
Error "Uexpected token {" when installing

### ISSUE THREAD

**Issue by justClizz** [railwayapp/cli#211]
When i installing the package, i got error:
```
import { createWriteStream } from "fs";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```

Can someone fix it/help me to solve this?

**Comment by devtomio** [comment]
What version of Node.js are you using?

**Comment by justClizz** [comment]
> What version of Node.js are you using?

11.13.0

**Comment by Milo123459** [comment]
> > What version of Node.js are you using?
> 
> 11.13.0

That's ancient. Please update your node version.

**Comment by justClizz** [comment]
> > > What version of Node.js are you using?
> > 
> > 
> > 11.13.0
> 
> That's ancient. Please update your node version.

Ok, i will update it

**Comment by devtomio** [comment]
> > What version of Node.js are you using?
> 
> 11.13.0

`import` statement are only supported in Node.js version 12 and above

**Comment by justClizz** [comment]
> > > What version of Node.js are you using?
> > 
> > 
> > 11.13.0
> 
> [`import`](https://nodejs.org/api/esm.html#modules-ecmascript-modules) statements are only supported in Node.js version 12 and above

so i must downgrade it?

**Comment by justClizz** [comment]
But, its just same got error like:
```
import { createWriteStream } from "fs";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by GrimZZZ-404** [comment]
Which Operating System are you using?

**Comment by justClizz** [comment]
> Which Operating System are you using?

Windows

**Comment by GrimZZZ-404** [comment]
> > Which Operating System are you using?
> 
> Windows

Use [scoop](https://github.com/railwayapp/scoop-railway)
