### ISSUE TITLE
npm i -g @railway/cli is broken in version 3.0.3

### ISSUE THREAD

**Issue by OanaSurdea** [railwayapp/cli#316]
I'm able to install `v2.1.0` just fine, but `v3.0.3` fails on multiple node & npm versions.

I've tested on node `v18.13.0`, `v18.14.2` & npm `v9.6.0`, `v9.5.0`.

This issue seems to be recurring and similar to a previously closed one https://github.com/railwayapp/cli/issues/219#issue-1236034230.

```
$ npm install -g @railway/cli

npm ERR! code 1
npm ERR! path C:\Users\Username\AppData\Roaming\nvm\v18.14.2\node_modules\@railway\cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./npm-install/postinstall.js
npm ERR! https://github.com/railwayapp/cli/releases/download/v3.0.3/railway-v3.0.3-x86_64-pc-windows-gnu.tar.gz
npm ERR! Error: Failed fetching the binary: Not Found
npm ERR!     at install (file:///C:/Users/Username/AppData/Roaming/nvm/v18.14.2/node_modules/@railway/cli/npm-install/postinstall.js:29:9)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Local\npm-cache\_logs\2023-03-04T07_08_33_096Z-debug-0.log
```

**Comment by MatWaligora** [comment]
I have an exact same issue on:
Win 11 Pro, Version 10.0.22621 compilation 22621

```C:\> npm install -g @railway/cli
npm ERR! code 1
npm ERR! path C:\Users\Username\AppData\Roaming\nvm\v16.15.0\node_modules\@railway\cli
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./npm-install/postinstall.js
npm ERR! https://github.com/railwayapp/cli/releases/download/v3.0.3/railway-v3.0.3-x86_64-pc-windows-gnu.tar.gz
npm ERR! Error: Failed fetching the binary: Not Found
npm ERR!     at install (file:///C:/Users/Username/AppData/Roaming/nvm/v16.15.0/node_modules/@railway/cli/npm-install/postinstall.js:29:9)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Local\npm-cache\_logs\2023-03-04T11_56_15_236Z-debug-0.log```

**Comment by nebulatgs** [comment]
Fixed in https://github.com/railwayapp/cli/releases/tag/v3.0.5
